"""`pcb-designer` command-line entry point.

Subcommands:
  validate   — typecheck a YAML config.
  gallery    — build INDEX.md gallery in a renders dir.
  init       — scaffold a new board project + YAML config from a
               packaged template (minimal | full_features).
  pipeline   — run the full chain (schematic → place → route → render → fab).
  schematic  — build the schematic (delegates via pipeline to the board's
               orchestrator, e.g. projects/<name>/tools/build_schematic.py).
  place      — place + DRC + render (via pipeline → place_components.py).
  route      — freerouting + zone fill (via pipeline → run_autorouter.py).
  render     — DIM PDF→PNG (via pipeline → render_dim.py).
  fab        — emit gerbers + drill + BOM + pos + zip release (calls
               `pcb_designer.fab.full_fab` directly — no board-specific
               orchestration needed).
  migrate    — one-shot extract from legacy script (TODO).

`pcb-designer` is registered as a console_script via pyproject.toml.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from pcb_designer import __version__
from pcb_designer.config import load_config


def cmd_validate(args: argparse.Namespace) -> int:
    cfg = load_config(args.config)
    print(
        f"OK: {cfg.project.full_name} ({cfg.project.version}) — "
        f"{len(cfg.placements)} placements, "
        f"{len(cfg.th_footprints)} through-hole, "
        f"{cfg.geometry_pcb.width:.0f}×{cfg.geometry_pcb.height:.0f} mm board"
    )
    return 0


def cmd_gallery(args: argparse.Namespace) -> int:
    """Build a markdown gallery (INDEX.md) of versioned PCB renders.

    Groups PNGs by their leading semantic version (vX.Y.Z[-descriptor])
    and emits one row per version with a one-line description if the
    file basename includes a hyphenated tag (the descriptor).

    Accepts any flat directory of `vX.Y.Z[-...]-<side>.png` files where
    `<side>` ∈ {top, bottom, dim-front, dim-back}. Skips non-image files.
    """
    import re

    renders_dir: Path = args.renders_dir.resolve()
    if not renders_dir.is_dir():
        print(f"ERROR: not a directory: {renders_dir}", file=sys.stderr)
        return 2

    ver_re = re.compile(r"^(v\d+\.\d+(?:\.\d+)?)(?:-([a-z0-9-]+?))?-(top|bottom|dim-front|dim-back)\.png$")

    groups: dict[str, dict[str, dict[str, str]]] = {}
    for p in sorted(renders_dir.iterdir()):
        if not p.is_file() or p.suffix.lower() != ".png":
            continue
        m = ver_re.match(p.name)
        if not m:
            continue
        ver, desc, side = m.group(1), m.group(2) or "", m.group(3)
        bucket = groups.setdefault(ver, {"desc": desc, "files": {}})
        if desc and not bucket["desc"]:
            bucket["desc"] = desc
        bucket["files"][side] = p.name

    def version_key(v: str):
        return tuple(int(x) for x in v.lstrip("v").split("."))

    sorted_versions = sorted(groups.keys(), key=version_key, reverse=True)

    out = renders_dir / "INDEX.md"
    lines: list[str] = []
    lines.append(f"# Renders gallery — {renders_dir.name}")
    lines.append("")
    lines.append(f"> Auto-generated by `pcb-designer gallery {renders_dir.name}`. "
                 "Edit the YAML config or re-run the renderer to update — do NOT hand-edit this file.")
    lines.append("")
    lines.append(f"Versions catalogued: **{len(sorted_versions)}**")
    lines.append("")

    for ver in sorted_versions:
        bucket = groups[ver]
        desc = bucket["desc"]
        files = bucket["files"]
        title = f"## {ver}"
        if desc:
            title += f" — {desc.replace('-', ' ')}"
        lines.append(title)
        lines.append("")
        # Render side-by-side table top + bottom (and dim variants if present)
        cells: list[tuple[str, str]] = []
        for side in ("top", "bottom", "dim-front", "dim-back"):
            if side in files:
                cells.append((side, files[side]))
        if cells:
            # Header row
            lines.append("| " + " | ".join(c[0] for c in cells) + " |")
            lines.append("|" + "|".join("---" for _ in cells) + "|")
            lines.append("| " + " | ".join(f"![{ver} {c[0]}]({c[1]})" for c in cells) + " |")
            lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    try:
        shown = out.relative_to(Path.cwd())
    except ValueError:      # renders dir outside cwd (boards live in their
        shown = out         # product repo — see "Where boards live", README)
    print(f"OK: wrote {shown} ({len(sorted_versions)} versions, "
          f"{sum(len(b['files']) for b in groups.values())} files)")
    return 0


def _load_cfg_and_pipeline(config_path: Path):
    from pcb_designer.pipeline import Pipeline
    cfg = load_config(config_path)
    return cfg, Pipeline(cfg, repo_root=Path.cwd())


def cmd_pipeline(args: argparse.Namespace) -> int:
    """Run the full chain or the listed --stages."""
    _, pipe = _load_cfg_and_pipeline(args.config)
    stages = args.stages.split(",") if args.stages else None
    result = pipe.run(stages)
    print(f"\nPipeline stages run: {result.stages_run}")
    return 0 if result.success else 1


def cmd_stage(stage_name: str):
    """Factory for single-stage commands (place/route/render/schematic)."""
    def _runner(args: argparse.Namespace) -> int:
        _, pipe = _load_cfg_and_pipeline(args.config)
        result = pipe.run([stage_name])
        return 0 if result.success else 1
    return _runner


def cmd_fab(args: argparse.Namespace) -> int:
    """Emit gerbers + drill + BOM + pos + release zip."""
    from pcb_designer.fab import full_fab
    cfg = load_config(args.config)
    repo_root = Path.cwd()
    pcb_path = cfg.pcb_path(repo_root)
    sch_path = cfg.sch_path(repo_root)
    releases_dir = cfg.releases_dir(repo_root)
    version = args.version or cfg.project.version
    zip_path = full_fab(pcb_path, sch_path, releases_dir, version)
    print(f"\nFab artefact: {zip_path}")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    """Scaffold a new board project + YAML config from a packaged template.

    Creates, under --dir (default: cwd):
        projects/<name>/{kicad,tools,renders,validation,releases}/
        projects/<name>/<name>.yaml   (from the chosen template)

    The generated config is loaded back through `load_config` before
    returning, so a scaffold that doesn't validate is a hard error.
    """
    from importlib.resources import files

    name = args.name
    if not re.fullmatch(r"[a-z0-9][a-z0-9._-]*", name):
        print(f"ERROR: board name must be a lowercase slug, got {name!r}",
              file=sys.stderr)
        return 2

    tpl_res = files("pcb_designer.templates").joinpath(f"{args.template}.yaml")
    try:
        tpl_text = tpl_res.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"ERROR: unknown template {args.template!r}", file=sys.stderr)
        return 2

    root: Path = args.dir.resolve()
    proj_dir = root / "projects" / name
    config_path = proj_dir / f"{name}.yaml"
    if config_path.exists():
        print(f"ERROR: {config_path} already exists — refusing to overwrite.",
              file=sys.stderr)
        return 2

    for sub in ("kicad", "tools", "renders", "validation", "releases"):
        (proj_dir / sub).mkdir(parents=True, exist_ok=True)

    text = tpl_text.replace("PROJECT-NAME", name)
    text = text.replace('"Human Readable Name"', f'"{args.full_name or name}"')
    text = text.replace("YOUR-ORG", args.vendor or "YOUR-ORG")
    config_path.write_text(text, encoding="utf-8")

    # Round-trip through the loader: a scaffold that doesn't parse is a bug.
    cfg = load_config(config_path)

    rel = config_path.relative_to(root) if root == Path.cwd() else config_path
    print(f"OK: scaffolded board '{cfg.project.name}' ({args.template} template)")
    print(f"  config:  {rel}")
    print(f"  project: {proj_dir.relative_to(root) if root == Path.cwd() else proj_dir}/")
    print("\nNext steps:")
    print(f"  1. Create the KiCad project: open KiCad → File → New Project →"
          f" projects/{name}/kicad/{name}")
    print("  2. Edit placements/pin_counts/nets in the YAML "
          "(see docs/CONFIG_REFERENCE.md and docs/PLACEMENT_GUIDE.md)")
    print(f"  3. Add orchestrator scripts under projects/{name}/tools/ "
          f"(copy projects/mt1/tools/ as a starting point)")
    print(f"  4. pcb-designer validate --config {rel}")
    return 0


def cmd_pending(name: str, reason: str):
    """Subcommands without an implementation yet."""
    def _runner(args: argparse.Namespace) -> int:
        print(f"pcb-designer {name}: {reason}", file=sys.stderr)
        return 2
    return _runner


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="pcb-designer",
        description="Reusable Python toolkit for KiCad-based PCB design.",
    )
    p.add_argument("--version", action="version", version=f"pcb-designer {__version__}")
    sub = p.add_subparsers(dest="command", required=True)

    # --- Functional, board-agnostic commands ---
    p_validate = sub.add_parser("validate", help="Typecheck a YAML config.")
    p_validate.add_argument("--config", required=True, type=Path)
    p_validate.set_defaults(func=cmd_validate)

    p_gallery = sub.add_parser("gallery", help="Build INDEX.md gallery in a renders dir.")
    p_gallery.add_argument("renders_dir", type=Path)
    p_gallery.set_defaults(func=cmd_gallery)

    # --- Pipeline + single-stage commands ---
    for name in ("schematic", "place", "route", "render"):
        sp = sub.add_parser(name, help=f"Run the {name} stage of the pipeline.")
        sp.add_argument("--config", required=True, type=Path)
        sp.set_defaults(func=cmd_stage(name))

    p_pipeline = sub.add_parser("pipeline",
                                help="Run the full chain or selected --stages.")
    p_pipeline.add_argument("--config", required=True, type=Path)
    p_pipeline.add_argument("--stages",
                            help="Comma-separated stages "
                                 "(e.g. place,route,render). Default: all.")
    p_pipeline.set_defaults(func=cmd_pipeline)

    p_fab = sub.add_parser("fab",
                           help="Emit gerbers + drill + BOM + pos + release zip.")
    p_fab.add_argument("--config", required=True, type=Path)
    p_fab.add_argument("--version",
                       help="Override the version tag (default: cfg.project.version).")
    p_fab.set_defaults(func=cmd_fab)

    p_init = sub.add_parser(
        "init",
        help="Scaffold a new board project + YAML config from a template.")
    p_init.add_argument("name", help="Board slug (e.g. mt2, sensor-hub).")
    p_init.add_argument("--template", choices=("minimal", "full_features"),
                        default="minimal",
                        help="Config template to start from (default: minimal).")
    p_init.add_argument("--dir", type=Path, default=Path("."),
                        help="Repo root to scaffold into (default: cwd).")
    p_init.add_argument("--full-name",
                        help="Human-readable board title for the config.")
    p_init.add_argument("--vendor",
                        help="Organisation name for the config's vendor field.")
    p_init.set_defaults(func=cmd_init)

    # --- Not-yet-implemented commands ---
    p_migrate = sub.add_parser("migrate",
                               help="Extract config from a legacy script (TODO).")
    p_migrate.set_defaults(func=cmd_pending(
        "migrate",
        "TODO — auto-extract PLACEMENTS/PIN_COUNT/PAD_HALF from a legacy place_components.py."))

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
